package org.ru.skypro.lessons.spring.EmployeeApplication.repository;

import java.util.List;

public class NameGenerator {

    static List <String> firstName = List.of("John",
            "Juanita",
            "Francis",
            "Charles",
            "Louis",
            "Florence",
            "Carmen",
            "Linda",
            "Barbara",
            "Cynthia",
            "Dana",
            "Mary",
            "Justin",
            "Roger",
            "Roger",
            "Grace",
            "Dean",
            "Tyler",
            "Raymond",
            "Gary",
            "Mark",
            "Andrew",
            "Dennis",
            "Jeremy",
            "Robert",
            "Dorothy",
            "Troy",
            "Raymond",
            "Maria",
            "Julia",
            "Mathew",
            "Charles",
            "Tyrone",
            "David",
            "Kathryn",
            "Mary",
            "Laurie",
            "Eric",
            "William",
            "Amanda",
            "Betty",
            "Daniel",
            "Lisa",
            "Frank",
            "Melvin",
            "Charlene",
            "Robert",
            "Michael",
            "Joann",
            "Joe");
    static List <String> lastName = List.of("Carlson",
            "Allen",
            "Wise",
            "Collins",
            "Ramirez",
            "Reese",
            "Davis",
            "Williams",
            "Bell",
            "Smith",
            "Frazier",
            "King",
            "Gomez",
            "Carter",
            "Meyer",
            "Stevens",
            "Edwards",
            "Freeman",
            "Brown",
            "Miller",
            "Norton",
            "Bates",
            "Williams",
            "Walker",
            "Welch",
            "Bates",
            "Green",
            "Bowen",
            "Foster",
            "Fitzgerald",
            "Christensen",
            "Clarke",
            "Moore",
            "Phillips",
            "Barker",
            "Powell",
            "Soto",
            "Taylor",
            "Murphy",
            "Wilson",
            "White",
            "Robinson",
            "Perez",
            "Robinson",
            "Jackson",
            "Smith",
            "Hicks",
            "Davis",
            "Mullins",
            "Garcia");

    public static String randomName () {
        String name = firstName.get((int) (Math.random()*50));
        String surname = lastName.get((int) (Math.random()*50));
        return surname + " " +name;
    }
}
