POST http://localhost:8080/employees/generate?number=25
###Он должен создавать множество новых сотрудников;

PUT http://localhost:8080/employees/1
###Он должен редактировать сотрудника с указанным id;

GET http://localhost:8080/employees/
###Он должен возвращать информацию о всех сотрудниках;

GET http://localhost:8080/employees/2
###Он должен возвращать информацию о сотруднике с переданным id;

DELETE http://localhost:8080/employees/1
###Он должен удалять сотрудника с переданным id;

GET http://localhost:8080/employees/salary/HigherThan?salary=10000
###Он должен возвращать всех сотрудников, зарплата которых выше переданного параметра salary.

GET http://localhost:8080/employees/withHighestSalary
###Он должен возвращать информацию о сотрудниках с самой высокой зарплатой в фирме;

GET http://localhost:8080/employees?position=
###Он должен принимать на вход опциональный параметр position и возвращать информацию о всех сотрудниках фирмы, указанной в параметре должности. Если параметр не указан, то возвращать необходимо всех сотрудников.

GET http://localhost:8080/employees/12/fullInfo
###Он должен возвращать полную информацию о сотруднике (имя, зарплата, название должности) с переданным в пути запроса идентификатором.

GET http://localhost:8080/employees/page?page=2
###Он должен возвращать информацию о сотрудниках, основываясь на номере страницы. Если страница не указана, то возвращается первая страница. Номера страниц начинаются с 0. Лимит на количество сотрудников на странице — 10 человек.
